[tool.poetry]
name        = "poetry-plugin-taskipy"
version     = "0.1.0"
description = "Poetry Plugin for Taskipy"
authors     = ["Taskipy Team"]
license     = "MIT"
readme      = "README.md"
packages    = [{ include = "poetry_plugin_taskipy" }]

[tool.poetry.dependencies]
python = "^3.7"
poetry = "1.4.2"

[build-system]
requires      = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
