name: Test

on: [push, pull_request]

jobs:
  test:
    name: Run the test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - '3.11'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Install poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'

      - name: Install dependencies
        run: poetry install --without lint

      - name: Run tests
        run: poetry run task test
